### ISSUE TITLE
Don't commit compiled javascript files

### ISSUE THREAD

**Issue by dpatti** [thedufer/JSONStreamify#1]
It makes it harder to develop and clutters source control. I know @ianthehenry handled this with hearsay and effing, so he might have some good opinions on the matter.

**Comment by thedufer** [comment]
Do you do the compilation during the install process, then?  @ianthehenry does this notify him

**Comment by dpatti** [comment]
He has some scripts in the package.json file, and one of them used to be a prepublish, but he took it out. Maybe he runs it manually before `npm publish`?

**Comment by ianthehenry** [comment]
Checking in the JS has one practical (dis?)advantage: it allows you to depend on specific unpublished commits via a Github URL. I decided this was sort of a misfeature and certainly not worth the incredibly annoying diffs.

I originally removed the `prepublish` script because of [this insanity](https://github.com/npm/npm/issues/3059). However, [looking into it more](https://github.com/npm/npm/issues/6887), it sounds like it would actually allow you to install via URL even with CS. I'll have to check that out.

Currently I'm just manually building before I publish.
